// <auto-generated />
using IEXTrading.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IEXTrading.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200412190758_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IEXTrading.Models.Company", b =>
                {
                    b.Property<string>("activity")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<string>("age_requirements");

                    b.Property<string>("days_of_week");

                    b.Property<string>("phone_number");

                    b.Property<string>("recreation_center");

                    b.Property<string>("times");

                    b.HasKey("activity");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("IEXTrading.Models.Equity", b =>
                {
                    b.Property<int>("EquityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Companyactivity");

                    b.Property<float>("change");

                    b.Property<float>("changeOverTime");

                    b.Property<float>("changePercent");

                    b.Property<float>("close");

                    b.Property<string>("date");

                    b.Property<float>("high");

                    b.Property<string>("label");

                    b.Property<float>("low");

                    b.Property<float>("open");

                    b.Property<string>("symbol");

                    b.Property<int>("unadjustedVolume");

                    b.Property<int>("volume");

                    b.Property<float>("vwap");

                    b.HasKey("EquityId");

                    b.HasIndex("Companyactivity");

                    b.ToTable("Equities");
                });

            modelBuilder.Entity("IEXTrading.Models.Equity", b =>
                {
                    b.HasOne("IEXTrading.Models.Company")
                        .WithMany("Equities")
                        .HasForeignKey("Companyactivity");
                });
#pragma warning restore 612, 618
        }
    }
}
